apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gstreamer.fullname" . }}
  labels:
    {{- include "gstreamer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gstreamer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gstreamer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MULTICAST_ADDRESS
              value: {{ .Values.gstreamer.multicastAddress | quote }}
            - name: UDP_PORT
              value: {{ .Values.gstreamer.udpPort | quote }}
            - name: BUFFER_DURATION
              value: {{ .Values.gstreamer.bufferDuration | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: udp
              containerPort: {{ .Values.gstreamer.udpPort }}
              protocol: UDP
          volumeMounts:
            - name: recordings
              mountPath: {{ .Values.gstreamer.recordingsPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            capabilities:
              {{- toYaml .Values.securityContext.capabilities | nindent 14 }}
      volumes:
        - name: recordings
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 