replicaCount: 1

image:
  repository: your-registry/gstreamer
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

# GStreamer specific configurations
gstreamer:
  udpPort: 5004
  multicastAddress: "239.255.1.1"
  bufferDuration: 0.5  # seconds
  recordingsPath: "/app/recordings"

# Security context
securityContext:
  capabilities:
    add: ["NET_ADMIN", "NET_RAW"] 